// Code generated by protoc-gen-go-http. DO NOT EDIT.
// versions:
// protoc-gen-go-http v2.1.1

package stats_v1

import (
	context "context"
	v1 "github.com/arktos-venture/buf/proto/quotes/v1"
	http "github.com/go-kratos/kratos/v2/transport/http"
	binding "github.com/go-kratos/kratos/v2/transport/http/binding"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the kratos package it is being compiled against.
var _ = new(context.Context)
var _ = binding.EncodeURL

const _ = http.SupportPackageIsVersion1

type StatsHTTPServer interface {
	Delete(context.Context, *v1.QuoteDeleteRequest) (*StatDelete, error)
	Last(context.Context, *v1.QuoteLastRequest) (*StatReply, error)
	Update(context.Context, *StatUpdateRequest) (*StatReply, error)
}

func RegisterStatsHTTPServer(s *http.Server, srv StatsHTTPServer) {
	r := s.Route("/")
	r.GET("/v1/stats/{exchange}/{ticker}", _Stats_Last2_HTTP_Handler(srv))
	r.PUT("/v1/stats/{exchange}/{ticker}", _Stats_Update4_HTTP_Handler(srv))
	r.DELETE("/v1/stats", _Stats_Delete12_HTTP_Handler(srv))
}

func _Stats_Last2_HTTP_Handler(srv StatsHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in v1.QuoteLastRequest
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		if err := ctx.BindVars(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, "/stats.v1.Stats/Last")
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.Last(ctx, req.(*v1.QuoteLastRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*StatReply)
		return ctx.Result(200, reply)
	}
}

func _Stats_Update4_HTTP_Handler(srv StatsHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in StatUpdateRequest
		if err := ctx.Bind(&in); err != nil {
			return err
		}
		if err := ctx.BindVars(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, "/stats.v1.Stats/Update")
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.Update(ctx, req.(*StatUpdateRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*StatReply)
		return ctx.Result(200, reply)
	}
}

func _Stats_Delete12_HTTP_Handler(srv StatsHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in v1.QuoteDeleteRequest
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, "/stats.v1.Stats/Delete")
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.Delete(ctx, req.(*v1.QuoteDeleteRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*StatDelete)
		return ctx.Result(200, reply)
	}
}

type StatsHTTPClient interface {
	Delete(ctx context.Context, req *v1.QuoteDeleteRequest, opts ...http.CallOption) (rsp *StatDelete, err error)
	Last(ctx context.Context, req *v1.QuoteLastRequest, opts ...http.CallOption) (rsp *StatReply, err error)
	Update(ctx context.Context, req *StatUpdateRequest, opts ...http.CallOption) (rsp *StatReply, err error)
}

type StatsHTTPClientImpl struct {
	cc *http.Client
}

func NewStatsHTTPClient(client *http.Client) StatsHTTPClient {
	return &StatsHTTPClientImpl{client}
}

func (c *StatsHTTPClientImpl) Delete(ctx context.Context, in *v1.QuoteDeleteRequest, opts ...http.CallOption) (*StatDelete, error) {
	var out StatDelete
	pattern := "/v1/stats"
	path := binding.EncodeURL(pattern, in, true)
	opts = append(opts, http.Operation("/stats.v1.Stats/Delete"))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "DELETE", path, nil, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, err
}

func (c *StatsHTTPClientImpl) Last(ctx context.Context, in *v1.QuoteLastRequest, opts ...http.CallOption) (*StatReply, error) {
	var out StatReply
	pattern := "/v1/stats/{exchange}/{ticker}"
	path := binding.EncodeURL(pattern, in, true)
	opts = append(opts, http.Operation("/stats.v1.Stats/Last"))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "GET", path, nil, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, err
}

func (c *StatsHTTPClientImpl) Update(ctx context.Context, in *StatUpdateRequest, opts ...http.CallOption) (*StatReply, error) {
	var out StatReply
	pattern := "/v1/stats/{exchange}/{ticker}"
	path := binding.EncodeURL(pattern, in, false)
	opts = append(opts, http.Operation("/stats.v1.Stats/Update"))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "PUT", path, in, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, err
}
