// Code generated by protoc-gen-go-http. DO NOT EDIT.
// versions:
// protoc-gen-go-http v2.1.1

package screener_v1

import (
	context "context"
	http "github.com/go-kratos/kratos/v2/transport/http"
	binding "github.com/go-kratos/kratos/v2/transport/http/binding"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the kratos package it is being compiled against.
var _ = new(context.Context)
var _ = binding.EncodeURL

const _ = http.SupportPackageIsVersion1

type ScreenerHTTPServer interface {
	Search(context.Context, *ScreenerRequest) (*ScreenerReplies, error)
}

func RegisterScreenerHTTPServer(s *http.Server, srv ScreenerHTTPServer) {
	r := s.Route("/")
	r.POST("/v1/screener", _Screener_Search0_HTTP_Handler(srv))
}

func _Screener_Search0_HTTP_Handler(srv ScreenerHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in ScreenerRequest
		if err := ctx.Bind(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, "/screener.v1.Screener/Search")
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.Search(ctx, req.(*ScreenerRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*ScreenerReplies)
		return ctx.Result(200, reply)
	}
}

type ScreenerHTTPClient interface {
	Search(ctx context.Context, req *ScreenerRequest, opts ...http.CallOption) (rsp *ScreenerReplies, err error)
}

type ScreenerHTTPClientImpl struct {
	cc *http.Client
}

func NewScreenerHTTPClient(client *http.Client) ScreenerHTTPClient {
	return &ScreenerHTTPClientImpl{client}
}

func (c *ScreenerHTTPClientImpl) Search(ctx context.Context, in *ScreenerRequest, opts ...http.CallOption) (*ScreenerReplies, error) {
	var out ScreenerReplies
	pattern := "/v1/screener"
	path := binding.EncodeURL(pattern, in, false)
	opts = append(opts, http.Operation("/screener.v1.Screener/Search"))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "POST", path, in, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, err
}
