// Code generated by protoc-gen-validate. DO NOT EDIT.
// source: proto/indices/v1/indices.proto

package indices_v1

import (
	"bytes"
	"errors"
	"fmt"
	"net"
	"net/mail"
	"net/url"
	"regexp"
	"sort"
	"strings"
	"time"
	"unicode/utf8"

	"google.golang.org/protobuf/types/known/anypb"
)

// ensure the imports are used
var (
	_ = bytes.MinRead
	_ = errors.New("")
	_ = fmt.Print
	_ = utf8.UTFMax
	_ = (*regexp.Regexp)(nil)
	_ = (*strings.Reader)(nil)
	_ = net.IPv4len
	_ = time.Duration(0)
	_ = (*url.URL)(nil)
	_ = (*mail.Address)(nil)
	_ = anypb.Any{}
	_ = sort.Sort
)

// Validate checks the field values on IndiceRequest with the rules defined in
// the proto definition for this message. If any rules are violated, the first
// error encountered is returned, or nil if there are no violations.
func (m *IndiceRequest) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on IndiceRequest with the rules defined
// in the proto definition for this message. If any rules are violated, the
// result is a list of violation errors wrapped in IndiceRequestMultiError, or
// nil if none found.
func (m *IndiceRequest) ValidateAll() error {
	return m.validate(true)
}

func (m *IndiceRequest) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	if l := utf8.RuneCountInString(m.GetTicker()); l < 2 || l > 16 {
		err := IndiceRequestValidationError{
			field:  "Ticker",
			reason: "value length must be between 2 and 16 runes, inclusive",
		}
		if !all {
			return err
		}
		errors = append(errors, err)
	}

	if len(errors) > 0 {
		return IndiceRequestMultiError(errors)
	}

	return nil
}

// IndiceRequestMultiError is an error wrapping multiple validation errors
// returned by IndiceRequest.ValidateAll() if the designated constraints
// aren't met.
type IndiceRequestMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m IndiceRequestMultiError) Error() string {
	var msgs []string
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m IndiceRequestMultiError) AllErrors() []error { return m }

// IndiceRequestValidationError is the validation error returned by
// IndiceRequest.Validate if the designated constraints aren't met.
type IndiceRequestValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e IndiceRequestValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e IndiceRequestValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e IndiceRequestValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e IndiceRequestValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e IndiceRequestValidationError) ErrorName() string { return "IndiceRequestValidationError" }

// Error satisfies the builtin error interface
func (e IndiceRequestValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sIndiceRequest.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = IndiceRequestValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = IndiceRequestValidationError{}

// Validate checks the field values on IndiceModifyRequest with the rules
// defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *IndiceModifyRequest) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on IndiceModifyRequest with the rules
// defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// IndiceModifyRequestMultiError, or nil if none found.
func (m *IndiceModifyRequest) ValidateAll() error {
	return m.validate(true)
}

func (m *IndiceModifyRequest) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for Ticker

	// no validation rules for Exchange

	// no validation rules for Description

	if len(errors) > 0 {
		return IndiceModifyRequestMultiError(errors)
	}

	return nil
}

// IndiceModifyRequestMultiError is an error wrapping multiple validation
// errors returned by IndiceModifyRequest.ValidateAll() if the designated
// constraints aren't met.
type IndiceModifyRequestMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m IndiceModifyRequestMultiError) Error() string {
	var msgs []string
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m IndiceModifyRequestMultiError) AllErrors() []error { return m }

// IndiceModifyRequestValidationError is the validation error returned by
// IndiceModifyRequest.Validate if the designated constraints aren't met.
type IndiceModifyRequestValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e IndiceModifyRequestValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e IndiceModifyRequestValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e IndiceModifyRequestValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e IndiceModifyRequestValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e IndiceModifyRequestValidationError) ErrorName() string {
	return "IndiceModifyRequestValidationError"
}

// Error satisfies the builtin error interface
func (e IndiceModifyRequestValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sIndiceModifyRequest.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = IndiceModifyRequestValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = IndiceModifyRequestValidationError{}

// Validate checks the field values on IndiceDeleteRequest with the rules
// defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *IndiceDeleteRequest) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on IndiceDeleteRequest with the rules
// defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// IndiceDeleteRequestMultiError, or nil if none found.
func (m *IndiceDeleteRequest) ValidateAll() error {
	return m.validate(true)
}

func (m *IndiceDeleteRequest) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	_IndiceDeleteRequest_Tickers_Unique := make(map[string]struct{}, len(m.GetTickers()))

	for idx, item := range m.GetTickers() {
		_, _ = idx, item

		if _, exists := _IndiceDeleteRequest_Tickers_Unique[item]; exists {
			err := IndiceDeleteRequestValidationError{
				field:  fmt.Sprintf("Tickers[%v]", idx),
				reason: "repeated value must contain unique items",
			}
			if !all {
				return err
			}
			errors = append(errors, err)
		} else {
			_IndiceDeleteRequest_Tickers_Unique[item] = struct{}{}
		}

		// no validation rules for Tickers[idx]
	}

	_IndiceDeleteRequest_Exchanges_Unique := make(map[string]struct{}, len(m.GetExchanges()))

	for idx, item := range m.GetExchanges() {
		_, _ = idx, item

		if _, exists := _IndiceDeleteRequest_Exchanges_Unique[item]; exists {
			err := IndiceDeleteRequestValidationError{
				field:  fmt.Sprintf("Exchanges[%v]", idx),
				reason: "repeated value must contain unique items",
			}
			if !all {
				return err
			}
			errors = append(errors, err)
		} else {
			_IndiceDeleteRequest_Exchanges_Unique[item] = struct{}{}
		}

		// no validation rules for Exchanges[idx]
	}

	if len(errors) > 0 {
		return IndiceDeleteRequestMultiError(errors)
	}

	return nil
}

// IndiceDeleteRequestMultiError is an error wrapping multiple validation
// errors returned by IndiceDeleteRequest.ValidateAll() if the designated
// constraints aren't met.
type IndiceDeleteRequestMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m IndiceDeleteRequestMultiError) Error() string {
	var msgs []string
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m IndiceDeleteRequestMultiError) AllErrors() []error { return m }

// IndiceDeleteRequestValidationError is the validation error returned by
// IndiceDeleteRequest.Validate if the designated constraints aren't met.
type IndiceDeleteRequestValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e IndiceDeleteRequestValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e IndiceDeleteRequestValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e IndiceDeleteRequestValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e IndiceDeleteRequestValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e IndiceDeleteRequestValidationError) ErrorName() string {
	return "IndiceDeleteRequestValidationError"
}

// Error satisfies the builtin error interface
func (e IndiceDeleteRequestValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sIndiceDeleteRequest.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = IndiceDeleteRequestValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = IndiceDeleteRequestValidationError{}

// Validate checks the field values on IndiceReply with the rules defined in
// the proto definition for this message. If any rules are violated, the first
// error encountered is returned, or nil if there are no violations.
func (m *IndiceReply) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on IndiceReply with the rules defined in
// the proto definition for this message. If any rules are violated, the
// result is a list of violation errors wrapped in IndiceReplyMultiError, or
// nil if none found.
func (m *IndiceReply) ValidateAll() error {
	return m.validate(true)
}

func (m *IndiceReply) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for Ticker

	// no validation rules for Exchange

	// no validation rules for Description

	if all {
		switch v := interface{}(m.GetQuote()).(type) {
		case interface{ ValidateAll() error }:
			if err := v.ValidateAll(); err != nil {
				errors = append(errors, IndiceReplyValidationError{
					field:  "Quote",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		case interface{ Validate() error }:
			if err := v.Validate(); err != nil {
				errors = append(errors, IndiceReplyValidationError{
					field:  "Quote",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		}
	} else if v, ok := interface{}(m.GetQuote()).(interface{ Validate() error }); ok {
		if err := v.Validate(); err != nil {
			return IndiceReplyValidationError{
				field:  "Quote",
				reason: "embedded message failed validation",
				cause:  err,
			}
		}
	}

	for idx, item := range m.GetCompanies() {
		_, _ = idx, item

		if all {
			switch v := interface{}(item).(type) {
			case interface{ ValidateAll() error }:
				if err := v.ValidateAll(); err != nil {
					errors = append(errors, IndiceReplyValidationError{
						field:  fmt.Sprintf("Companies[%v]", idx),
						reason: "embedded message failed validation",
						cause:  err,
					})
				}
			case interface{ Validate() error }:
				if err := v.Validate(); err != nil {
					errors = append(errors, IndiceReplyValidationError{
						field:  fmt.Sprintf("Companies[%v]", idx),
						reason: "embedded message failed validation",
						cause:  err,
					})
				}
			}
		} else if v, ok := interface{}(item).(interface{ Validate() error }); ok {
			if err := v.Validate(); err != nil {
				return IndiceReplyValidationError{
					field:  fmt.Sprintf("Companies[%v]", idx),
					reason: "embedded message failed validation",
					cause:  err,
				}
			}
		}

	}

	if all {
		switch v := interface{}(m.GetCreatedAt()).(type) {
		case interface{ ValidateAll() error }:
			if err := v.ValidateAll(); err != nil {
				errors = append(errors, IndiceReplyValidationError{
					field:  "CreatedAt",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		case interface{ Validate() error }:
			if err := v.Validate(); err != nil {
				errors = append(errors, IndiceReplyValidationError{
					field:  "CreatedAt",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		}
	} else if v, ok := interface{}(m.GetCreatedAt()).(interface{ Validate() error }); ok {
		if err := v.Validate(); err != nil {
			return IndiceReplyValidationError{
				field:  "CreatedAt",
				reason: "embedded message failed validation",
				cause:  err,
			}
		}
	}

	if all {
		switch v := interface{}(m.GetUpdatedAt()).(type) {
		case interface{ ValidateAll() error }:
			if err := v.ValidateAll(); err != nil {
				errors = append(errors, IndiceReplyValidationError{
					field:  "UpdatedAt",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		case interface{ Validate() error }:
			if err := v.Validate(); err != nil {
				errors = append(errors, IndiceReplyValidationError{
					field:  "UpdatedAt",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		}
	} else if v, ok := interface{}(m.GetUpdatedAt()).(interface{ Validate() error }); ok {
		if err := v.Validate(); err != nil {
			return IndiceReplyValidationError{
				field:  "UpdatedAt",
				reason: "embedded message failed validation",
				cause:  err,
			}
		}
	}

	if len(errors) > 0 {
		return IndiceReplyMultiError(errors)
	}

	return nil
}

// IndiceReplyMultiError is an error wrapping multiple validation errors
// returned by IndiceReply.ValidateAll() if the designated constraints aren't met.
type IndiceReplyMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m IndiceReplyMultiError) Error() string {
	var msgs []string
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m IndiceReplyMultiError) AllErrors() []error { return m }

// IndiceReplyValidationError is the validation error returned by
// IndiceReply.Validate if the designated constraints aren't met.
type IndiceReplyValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e IndiceReplyValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e IndiceReplyValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e IndiceReplyValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e IndiceReplyValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e IndiceReplyValidationError) ErrorName() string { return "IndiceReplyValidationError" }

// Error satisfies the builtin error interface
func (e IndiceReplyValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sIndiceReply.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = IndiceReplyValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = IndiceReplyValidationError{}

// Validate checks the field values on IndiceShortReplies with the rules
// defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *IndiceShortReplies) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on IndiceShortReplies with the rules
// defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// IndiceShortRepliesMultiError, or nil if none found.
func (m *IndiceShortReplies) ValidateAll() error {
	return m.validate(true)
}

func (m *IndiceShortReplies) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	for idx, item := range m.GetResults() {
		_, _ = idx, item

		if all {
			switch v := interface{}(item).(type) {
			case interface{ ValidateAll() error }:
				if err := v.ValidateAll(); err != nil {
					errors = append(errors, IndiceShortRepliesValidationError{
						field:  fmt.Sprintf("Results[%v]", idx),
						reason: "embedded message failed validation",
						cause:  err,
					})
				}
			case interface{ Validate() error }:
				if err := v.Validate(); err != nil {
					errors = append(errors, IndiceShortRepliesValidationError{
						field:  fmt.Sprintf("Results[%v]", idx),
						reason: "embedded message failed validation",
						cause:  err,
					})
				}
			}
		} else if v, ok := interface{}(item).(interface{ Validate() error }); ok {
			if err := v.Validate(); err != nil {
				return IndiceShortRepliesValidationError{
					field:  fmt.Sprintf("Results[%v]", idx),
					reason: "embedded message failed validation",
					cause:  err,
				}
			}
		}

	}

	// no validation rules for Total

	if len(errors) > 0 {
		return IndiceShortRepliesMultiError(errors)
	}

	return nil
}

// IndiceShortRepliesMultiError is an error wrapping multiple validation errors
// returned by IndiceShortReplies.ValidateAll() if the designated constraints
// aren't met.
type IndiceShortRepliesMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m IndiceShortRepliesMultiError) Error() string {
	var msgs []string
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m IndiceShortRepliesMultiError) AllErrors() []error { return m }

// IndiceShortRepliesValidationError is the validation error returned by
// IndiceShortReplies.Validate if the designated constraints aren't met.
type IndiceShortRepliesValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e IndiceShortRepliesValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e IndiceShortRepliesValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e IndiceShortRepliesValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e IndiceShortRepliesValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e IndiceShortRepliesValidationError) ErrorName() string {
	return "IndiceShortRepliesValidationError"
}

// Error satisfies the builtin error interface
func (e IndiceShortRepliesValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sIndiceShortReplies.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = IndiceShortRepliesValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = IndiceShortRepliesValidationError{}

// Validate checks the field values on IndiceDelete with the rules defined in
// the proto definition for this message. If any rules are violated, the first
// error encountered is returned, or nil if there are no violations.
func (m *IndiceDelete) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on IndiceDelete with the rules defined
// in the proto definition for this message. If any rules are violated, the
// result is a list of violation errors wrapped in IndiceDeleteMultiError, or
// nil if none found.
func (m *IndiceDelete) ValidateAll() error {
	return m.validate(true)
}

func (m *IndiceDelete) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for Total

	if len(errors) > 0 {
		return IndiceDeleteMultiError(errors)
	}

	return nil
}

// IndiceDeleteMultiError is an error wrapping multiple validation errors
// returned by IndiceDelete.ValidateAll() if the designated constraints aren't met.
type IndiceDeleteMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m IndiceDeleteMultiError) Error() string {
	var msgs []string
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m IndiceDeleteMultiError) AllErrors() []error { return m }

// IndiceDeleteValidationError is the validation error returned by
// IndiceDelete.Validate if the designated constraints aren't met.
type IndiceDeleteValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e IndiceDeleteValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e IndiceDeleteValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e IndiceDeleteValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e IndiceDeleteValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e IndiceDeleteValidationError) ErrorName() string { return "IndiceDeleteValidationError" }

// Error satisfies the builtin error interface
func (e IndiceDeleteValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sIndiceDelete.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = IndiceDeleteValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = IndiceDeleteValidationError{}

// Validate checks the field values on IndiceShortReplies_Result with the rules
// defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *IndiceShortReplies_Result) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on IndiceShortReplies_Result with the
// rules defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// IndiceShortReplies_ResultMultiError, or nil if none found.
func (m *IndiceShortReplies_Result) ValidateAll() error {
	return m.validate(true)
}

func (m *IndiceShortReplies_Result) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for Ticker

	// no validation rules for Exchange

	if all {
		switch v := interface{}(m.GetCreatedAt()).(type) {
		case interface{ ValidateAll() error }:
			if err := v.ValidateAll(); err != nil {
				errors = append(errors, IndiceShortReplies_ResultValidationError{
					field:  "CreatedAt",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		case interface{ Validate() error }:
			if err := v.Validate(); err != nil {
				errors = append(errors, IndiceShortReplies_ResultValidationError{
					field:  "CreatedAt",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		}
	} else if v, ok := interface{}(m.GetCreatedAt()).(interface{ Validate() error }); ok {
		if err := v.Validate(); err != nil {
			return IndiceShortReplies_ResultValidationError{
				field:  "CreatedAt",
				reason: "embedded message failed validation",
				cause:  err,
			}
		}
	}

	if all {
		switch v := interface{}(m.GetUpdatedAt()).(type) {
		case interface{ ValidateAll() error }:
			if err := v.ValidateAll(); err != nil {
				errors = append(errors, IndiceShortReplies_ResultValidationError{
					field:  "UpdatedAt",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		case interface{ Validate() error }:
			if err := v.Validate(); err != nil {
				errors = append(errors, IndiceShortReplies_ResultValidationError{
					field:  "UpdatedAt",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		}
	} else if v, ok := interface{}(m.GetUpdatedAt()).(interface{ Validate() error }); ok {
		if err := v.Validate(); err != nil {
			return IndiceShortReplies_ResultValidationError{
				field:  "UpdatedAt",
				reason: "embedded message failed validation",
				cause:  err,
			}
		}
	}

	if len(errors) > 0 {
		return IndiceShortReplies_ResultMultiError(errors)
	}

	return nil
}

// IndiceShortReplies_ResultMultiError is an error wrapping multiple validation
// errors returned by IndiceShortReplies_Result.ValidateAll() if the
// designated constraints aren't met.
type IndiceShortReplies_ResultMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m IndiceShortReplies_ResultMultiError) Error() string {
	var msgs []string
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m IndiceShortReplies_ResultMultiError) AllErrors() []error { return m }

// IndiceShortReplies_ResultValidationError is the validation error returned by
// IndiceShortReplies_Result.Validate if the designated constraints aren't met.
type IndiceShortReplies_ResultValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e IndiceShortReplies_ResultValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e IndiceShortReplies_ResultValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e IndiceShortReplies_ResultValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e IndiceShortReplies_ResultValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e IndiceShortReplies_ResultValidationError) ErrorName() string {
	return "IndiceShortReplies_ResultValidationError"
}

// Error satisfies the builtin error interface
func (e IndiceShortReplies_ResultValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sIndiceShortReplies_Result.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = IndiceShortReplies_ResultValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = IndiceShortReplies_ResultValidationError{}
